sudo: required

services:
   - docker

before_install:
   - docker build -t infoLightspace/docker-react -f Dockerfile.dev .

script:
  - docker run infoLightspace/docker-react npm run test -- --coverage